spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    mail:
        host: smtp.gmail.com
        port: 587
        username: wojjmaj22@gmail.com
        password:
        test-connection: true
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: 8443
    ssl:
        key-store: keystore.jks
        key-store-password: password
        key-store-type: jks
        key-alias: notes
        key-password: password
